### ISSUE TITLE
How to reference public key in knock.rb (config.token_public_key) ?

### ISSUE THREAD

**Issue by jessecravens** [nsarno/knock#148]
I am trying to properly configure an app that uses auth0js v8.2.0 to use RS256. Since Auth0 is returning a token signed with RS256. I've debugged it down to here: https://github.com/jwt/ruby-jwt/issues/115

One theory that I have is that my reference in `config.token_public_key` is improper.

```
Knock.setup do |config|
  config.token_audience = -> { Rails.application.secrets.auth0_client_id }
  config.token_secret_signature_key = -> { Rails.application.secrets.auth0_client_secret }
  config.token_public_key = ????
end
```

I've tried every which way I can think of, but this method`public_key.verify(OpenSSL::Digest.new(algorithm.sub('RS', 'sha')), signature, signing_input)` continues to raise a no method error:

```
no method 'verify' for type String.
``` 

Does anyone have a working example?
Or is there something more fundamental that I am missing here?

**Comment by jessecravens** [comment]
I figured this out .. for anyone else stumped by this, here is my solution:

In secrets.yml:

```
development:
  secret_key_base: <secret>
  auth0_client_id: <secret>
  auth0_client_secret: <secret>
  auth0_rsa_domain: <link from AuthO : Clients >Advanced Settings > Endpoints > JSON Web Key Set
```

In knock.rb: 
```
  jwks_raw = Net::HTTP.get URI(Rails.application.secrets.auth0_rsa_domain)
  jwks_keys = Array(JSON.parse(jwks_raw)['keys'])
  config.token_public_key = OpenSSL::X509::Certificate.new(Base64.decode64(jwks_keys[0]['x5c'].first)).public_key
```
